# Generated by Django 5.0.2 on 2024-02-19 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_site', '0002_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ADRAR', 'ADRAR'), ('TAMEST', 'TAMEST'), ('REGGANE', 'REGGANE'), ('IN ZGHMIR', 'IN ZGHMIR'), ('TIT', 'TIT'), ('TSABIT', 'TSABIT'), ('ZAOUIET KOUNTA', 'ZAOUIET KOUNTA'), ('AOULEF', 'AOULEF'), ('TIMEKTEN', 'TIMEKTEN'), ('TAMANTIT', 'TAMANTIT'), ('FENOUGHIL', 'FENOUGHIL'), ('SALI', 'SALI'), ('AKABLI', 'AKABLI'), ('OULED AHMED TIMMI', 'OULED AHMED TIMMI'), ('BOUDA', 'BOUDA'), ('SEBAA', 'SEBAA'), ('CHLEF', 'CHLEF'), ('TENES', 'TENES'), ('BENAIRIA', 'BENAIRIA'), ('EL KARIMIA', 'EL KARIMIA'), ('TADJENA', 'TADJENA'), ('TAOUGRITE', 'TAOUGRITE'), ('BENI HAOUA', 'BENI HAOUA'), ('SOBHA', 'SOBHA'), ('HARCHOUN', 'HARCHOUN'), ('OULED FARES', 'OULED FARES'), ('SIDI AKKACHA', 'SIDI AKKACHA'), ('BOUKADIR', 'BOUKADIR'), ('BENI RACHED', 'BENI RACHED'), ('TALASSA', 'TALASSA'), ('HERENFA', 'HERENFA'), ('OUED GOUSSINE', 'OUED GOUSSINE'), ('DAHRA', 'DAHRA'), ('OULED ABBES', 'OULED ABBES'), ('SENDJAS', 'SENDJAS'), ('ZEBOUDJA', 'ZEBOUDJA'), ('OUED SLY', 'OUED SLY')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('أدرار', 'أدرار'), ('الشلف', 'الشلف'), ('الأغواط', 'الأغواط'), ('أم البواقي', 'أم البواقي'), ('باتنة', 'باتنة'), ('بجاية', 'بجاية'), ('بسكرة', 'بسكرة'), ('بشار', 'بشار'), ('البليدة', 'البليدة'), ('البويرة', 'البويرة'), ('تمنراست', 'تمنراست'), ('تبسة', 'تبسة'), ('تلمسان', 'تلمسان'), ('تيارت', 'تيارت'), ('تيزي وزو', 'تيزي وزو'), ('الجزائر العاصمة', 'الجزائر العاصمة'), ('الجلفة', 'الجلفة'), ('جيجل', 'جيجل'), ('سطيف', 'سطيف'), ('سعيدة', 'سعيدة'), ('سكيكدة', 'سكيكدة'), ('سيدي بلعباس', 'سيدي بلعباس'), ('عنابة', 'عنابة'), ('قالمة', 'قالمة'), ('قسنطينة', 'قسنطينة'), ('المدية', 'المدية'), ('مستغانم', 'مستغانم'), ('المسيلة', 'المسيلة'), ('معسكر', 'معسكر'), ('ورقلة', 'ورقلة'), ('وهران', 'وهران'), ('البيض', 'البيض'), ('إليزي', 'إليزي'), ('برج بوعريريج', 'برج بوعريريج'), ('بومرداس', 'بومرداس'), ('الطارف', 'الطارف'), ('تندوف', 'تندوف'), ('تيسمسيلت', 'تيسمسيلت'), ('الوادي', 'الوادي'), ('خنشلة', 'خنشلة'), ('سوق أهراس', 'سوق أهراس'), ('تيبازة', 'تيبازة'), ('ميلة', 'ميلة'), ('عين الدفلى', 'عين الدفلى'), ('النعامة', 'النعامة'), ('عين تموشنت', 'عين تموشنت'), ('غرداية', 'غرداية'), ('غليزان', 'غليزان'), ('تيميمون', 'تيميمون'), ('برج باجي مختار', 'برج باجي مختار'), ('أولاد جلال', 'أولاد جلال'), ('بني عباس', 'بني عباس'), ('عين صالح', 'عين صالح'), ('عين قزام', 'عين قزام'), ('تقرت', 'تقرت'), ('جانت', 'جانت'), ('المغير', 'المغير'), ('المنيعة', 'المنيعة')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20)),
                ('numero', models.IntegerField()),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_site.commune')),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_site.wilaya')),
            ],
        ),
        migrations.AddField(
            model_name='commune',
            name='wilaya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_site.wilaya'),
        ),
    ]
